name = "Double64s"
uuid = "f7056ef7-10e8-4267-995d-66cee1eee17a"
authors = ["Jeffrey Sarnoff <JeffreySarnoff@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
ErrorfreeArithmetic = "90fa49ef-747e-5e6f-a989-263ba693cf1a"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Gaius = "bffe22d1-cb55-4f4e-ac2c-f4dd4bf58912"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "LinearAlgebra", "BenchmarkTools", "Quadmath"]

[compat]
Quadmath = "0"
ErrorfreeArithmetic = "0"
BenchmarkTools = "0"
StructArrays = "0"
LoopVectorization = "0"
Gaius = "0"
Documenter = "0"
julia = "1"
